tasks:
  oxlint:
    description: "Run Oxlint for fast linting"
    script: |
      [ -z ${CI:-} ] && FIX_FLAG="--fix"

      oxlint --deny-warnings --type-aware ${FIX_FLAG:-} .
    inputs:
      - "**/*.{cjs,js,mjs,ts,tsx}"
      - "*.{cjs,js,mjs,ts,tsx}"
      - ".oxlintrc.json"
      - "/projects/oxlint-rules/*.oxlintrc.json"
    toolchain: "node"
